### PR TITLE
Dockerize the app

### PR DESCRIPTION
**Pull request by gardner**
Hi Daniel,
  there are a lot of changes here:

- The `docker-compose.yml` is geared for local development.
- The Dockerfile.prod in the root directory gets built and published to Docker Hub whenever you push to master.
- The Dockerfile in the api/ directory gets built and published to Docker Hub whenever you push to master.
- There is a new workflow in the `.github/` directory that does these actions. You must configure `DOCKER_HUB_PASSWORD` and `DOCKER_HUB_USERNAME` secrets in your project settings for this to work.
- I rejigged your config setup to work with Docker and its use of environment variables.

Let me know if you want to meet up on this and we can go over it together.

### CODE REVIEW

**Comment by gardner** [comment]
The images are being automatically built and uploaded from my branch:

- https://hub.docker.com/repository/docker/gardner/linkwarden-api
- https://hub.docker.com/repository/docker/gardner/linkwarden

**Comment by gardner** [comment]
You can see the workflow running here: https://github.com/gardner/link-warden/actions/workflows/build_images.yml

**Comment by Daniel31x13** [comment]
Hello Gardner,
Thanks you for contributing.
Can you please explain more on running it?
I ran `docker compose up` in the main folder but ran into problems (from `permission denied` to `CORS` error).
Also you said:

> You must configure DOCKER_HUB_PASSWORD and DOCKER_HUB_USERNAME secrets in your project settings for this to work.

What project setting?

Thanks again.

**Comment by gardner** [comment]
Heya, the CORS issue may be related to API_HOST not using localhost as the hostname. Chrome has some exceptions around localhost for security related things. I don't think this extends to 127.0.0.1 or 0.0.0.0.

For permission denied errors you would want to check to make sure that the `media/` folder exists in the root of your repo, where the `docker-compose.yml` file is.

If you can copy and paste the error messages or upload screenshots that would make it easier to debug. Here's a video of me testing it locally: https://youtu.be/D2SwK_8iEYY

**Comment by Daniel31x13** [comment]
Hello there,
Alright so there's a good news and a bad news:
The good news is that this worked perfectly on windows (`docker compose up` DONE!)

The bad news is it still doesn't work on linux (ubuntu), 
I ran `ls -la` and it shows both the node modules and the media folder owners were root so I changed the ownership and met a new error: `MongoServerError: Authentication failed.`

I'm ok if you want a voice/video chat or screenshare (7:30am-12 EDT) so email/DM me a preferred time.

Thanks again!
 
Screenshot from 2022-06-19 09-02-24

**Comment by gardner** [comment]
Permissions on docker bind mount volumes are always a bit problematic. It might be easier to make it a named volume from that perspective. I just wanted it to be easy to see the files in the directory. 

I was able to remove the authentication from mongo entirely and it works. This looks like this:

```
services:
  mongo:
    image: mongo
    restart: unless-stopped

  link-warden-api:
    build: ./api
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - ./media:/media
      - ./api:/home/node
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - mongo
```

I pushed this change. You can destroy all the data in the docker-compose containers by doing a `docker-compose down -v`. You will want to do this before doing  `docker-compose up -d`.

Are you running `docker-compose with `sudo`? Or did you do the post-installation steps for linux? https://docs.docker.com/engine/install/linux-postinstall/

**Comment by Daniel31x13** [comment]
It's now working perfectly, I've also added the media (now storage) folder without docker creating it for me and the error completely goes away.

Thanks a lot! <3

**Comment by gardner** [comment]
I submitted a fix for the permissions issue in https://github.com/Daniel31x13/link-warden/pull/10

**Pull request merged**
